alex/69/mongapp/config/routes.rb
Rails.application.routes.draw do
  resources :artists do
    get '/show' => 'artists#show'
  end

  root 'welcome#index'
end

alex/69/mongapp/app/models/artist.rb
class Artist
  include Mongoid::Document
  store_in collection: "artist"
  field :name, type: String
  field :area, type: String
  #field :id, type: Int 
  #field :id, type: Integer
end

alex/69/mongapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

alex/69/mongapp/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.limit(10)
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    @artist = Artist.find_by(name: params[:name])
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      ActionController::Parameters.permit_all_parameters = true
      @artist = Artist.find(name: params[:name], :limit => 5)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.fetch(:artist, {})
    end

    
end

alex/69/mongapp/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

alex/69/mongapp/app/helpers/application_helper.rb
module ApplicationHelper
end

alex/69/mongapp/app/helpers/artists_helper.rb
module ArtistsHelper
end

alex/69/mongapp/app/helpers/welcome_helper.rb
module WelcomeHelper
end

alex/69/mongapp/app/views/artists/_form.html.erb
<%= form_with(model: artist, local: true) do |form| %>
  <% if artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

alex/69/mongapp/app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

alex/69/mongapp/app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="color:blue">Artists</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.name %></td>
        <td><%= artist.area %></td>
        <!--<td><%= link_to 'Show', @artist %><td> -->
        <td style="padding: 2%"><a href="artists/show?name=<%=  artist.name %>">show</a></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<div style="float:right"><%= link_to 'New Artist', new_artist_path %></div>

alex/69/mongapp/app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Back', artists_path %>

alex/69/mongapp/app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>
<h1 style="color:blue">Show the selected artist name</h1>
<br/>
<body style="width:80%">
    <table>
        <td><%= @artist.name %></td>
        <td><%= @artist.area %></td>
    </table>
    <br/>
    <%# <%= link_to 'Edit', edit_artist_path(@artist) %>
    <div style="float:right"><%= link_to 'Back', artists_path %></div>
</body>

alex/69/mongapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mongapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'artists', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

alex/69/mongapp/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>hi alex</p>